GOOGLE_API_KEY=AIzaSyBHLe14o1rLCTN-2tnqGBXAZ8o7JPoeCe4
QDRANT_URL=https://a0561d2a-d72a-48ce-9bcc-99ecc046d88f.europe-west3-0.gcp.cloud.qdrant.io:6333
QDRANT_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIiwiZXhwIjoxNzQ2NjI3MTA3fQ.WnBBx7YVIRQFgsP0tvwh4cyz5ORvRYZNh_ofUG65moM
